### ISSUE TITLE
spkt_Checkboxes not found

### ISSUE THREAD

**Issue by khongten001** [haword/spktoolbar#1]
As the title, the spkt_Checkboxes unit not found

**Comment by haword** [comment]
fixed

**Comment by khongten001** [comment]
Thank you for uploadign spkt_Checkboxes. But the file spkte_AppearanceEditor is not found

**Comment by haword** [comment]
fixed

**Comment by khongten001** [comment]
Thank you very much. One more thing, please add spkt_Checkboxes into the package.
